### ISSUE TITLE
Feature Request: Group menu items in sections instead of folders

### ISSUE THREAD

**Issue by dbondarchuk** [knrdl/hubleys-dashboard#223]
Love the dashboard!
One thing that I would love to see for myself is the ability to display the menu option as a group instead of a folder.
It will save +1 click to reach the needed service and time to wonder where the service is for non-admin users. 
It could be a switch either on system level or user level

Something like this:
<img width="1295" alt="image" src="https://github.com/knrdl/hubleys-dashboard/assets/12608684/c5b13682-46be-449a-ac3a-bd6af7c46cf0">

**Comment by K-J-VV** [comment]
+1, really like the example image as well

Only thing to add, if implemented this should not be an "either, or" feature. Rather, please keep the option to create folders as I can see it being useful from an organization standpoint to have both sections and folder/menu trees within items

**Comment by knrdl** [comment]
I like the idea too. I would keep the menu system as it is, but add a new section system. The config might look something like this:

```yaml
tiles:
  - title: Media
    section: true  # <- this controls the display as section
    allow: [group:media]
    tiles:
      - title: Plex
        logo: plex
        url: ...
      - title: JellyFin
        logo: jellyfin
        url: ...
  - title: Home
    section: true  # <- this controls the display as section
    ...
```

**Comment by dbondarchuk** [comment]
I think it should be a toggle in user setting:
<img width="782" alt="image" src="https://github.com/knrdl/hubleys-dashboard/assets/12608684/78bc5954-6c9b-4780-b57d-fc14c8b095ee">

**Comment by dbondarchuk** [comment]
but i like the idea with section: you can group folders in sections with that approach

Maybe instead of `section: true` it should be `display: section` with `menu` as the default option? That way it could be extended later

**Comment by dbondarchuk** [comment]
As #233 was merged, we can close this one
thanks, @knrdl !

**Comment by K-J-VV** [comment]
Is this available in :edge? Can't seem to get my dashboard to display with sections (referenced here for the config format https://github.com/knrdl/hubleys-dashboard/pull/233)

**Comment by dbondarchuk** [comment]
Probably due to #224. As my PR was changed and at the moment it requires you to add `allow: true` to the tiles.

**Comment by knrdl** [comment]
I have not made up my mind yet about the `allow: true` thing. @dbondarchuk suggested in #224 and #240 removing it and always show tiles when no `allow` rule is specified. This would make the config easier but may expose tiles by accident (when overlooking the missing `allow` rule). The current behavior is to always hide root tiles and sections without `allow`  and show a warning about it on server start. This has the better safety but maybe is harder to debug.
@K-J-VV what is your opinion as a user of the software and its config?

**Comment by dbondarchuk** [comment]
@knrdl I agree that **ROOT** tiles and sections should always have explicit `allow`, but for tiles under the section, `allow: true` should be implicit, because as a user, I can give access to all my applications under the section to a specific scope of users.

**Comment by K-J-VV** [comment]
@knrdl I think @dbondarchuk wanting to simplify the config makes sense. Having to create an "allow: rule" for each item is tedious & makes a cluttered file

By default, enforcing an "allow: rule" on ROOT all sections makes sense. I agree not requiring an allow rule can inadvertently lead to security issues (it is also not too difficult to set in the config). All subtree items within a section should fall beneath the ROOT's allow rule.  Then users can select/specify Items within the sub-tree further if needed

In the example below, I want the entire Section accessible by group1. However, I want a specific item (Sverdle) to only be accessible by user1 of group1


```
sections:
  - allow: [ group:group1 ]
    tiles:
      - title: Home
        url: https://home.example.com
        logo: Home-Icon
      - title: Logout
        url: https://auth.example.com/logout
        logo: Logout-Icon
        menu:
          - title: Profile
            logo: Profile-Icon
            url: https://auth.example.com/profile
          - title: Sverdle
            allow: [ user:1 ]  
            url: /sverdle
            logo: Sverdle-Icon
```
