### ISSUE TITLE
Compose and Demo error out

### ISSUE THREAD

**Issue by PDXUser** [knrdl/hubleys-dashboard#45]
The following error I get is as follows:

`mkdir: can't create directory '/data/logos': Permission denied`

I am doing this as a root user in both Arch and Debian 11 system for evaluation of replacing Dashy. 
This stops my testing dead in it's tracks.

**Comment by knrdl** [comment]
Hi, thanks for your feedback. The problem is that the software in the container runs with reduced privileges (not as root user). So it cannot create the `/data` folder on it's own and can't work with the `/data` folder if it is owned by root.

Please try the following:
```bash
mkdir /tmp/hubleys  # create a folder on the host
chown -R 1000:1000 /tmp/hubleys  # giving it the right permissions (user & group)
docker run -it --rm -v /tmp/hubleys:/data ghcr.io/knrdl/hubleys-dashboard  # test it
```
Now the software should startup and you can continue testing :)

**Comment by PDXUser** [comment]
If I do not want to use a proxy, I get this now:
 500 forward auth not configured

My Compose file - I do not want to use a reverse proxy in my instance so I commented that out:
`services:
  hubleys:
    image: ghcr.io/knrdl/hubleys-dashboard
    hostname: hubleys
    restart: unless-stopped
#    environment:
#      OPENWEATHERMAP_API_KEY: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  # get a free api key: https://home.openweathermap.org/api_keys
#      UNSPLASH_API_KEY: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  # get a free api key (Access Key): https://unsplash.com/oauth/applications
#    ADMIN_USERIDS: PDXuser
    volumes:
      - /docker/appdata/hubleys/:/data  # run `chown -R 1000:1000 ./data` on the host to fix folder permissions
#    networks:
#      - proxy  # must be reachable by the reverse proxy
    mem_limit: 100m
    ports:
      - '4002:3000'
`
How do I get around the forward auth issue?

**Comment by knrdl** [comment]
Hubleys is really meant to be multi user capable which requires a reverse proxy ... However you could simply go with the Demo mode and use it as single user mode instead. Try this one:

```yaml
version: '2.4'
services:
  hubleys:
    image: ghcr.io/knrdl/hubleys-dashboard
    hostname: hubleys
    restart: unless-stopped
    environment:
      DEMO_MODE: '1'
      ORIGIN: 'http://nas:4002'  # <- what you type in the browser address bar to open hubleys
    volumes:
      - /docker/appdata/hubleys/data/:/data
      - /docker/appdata/hubleys/config.yml:/app/demo/config.yml
    mem_limit: 100m
    ports:
      - '4002:3000'
```

You will need the config.yml file to get started, see the example here: https://github.com/knrdl/hubleys-dashboard/blob/main/docs/config.yml
