### ISSUE TITLE
[BUG] Internal Error when menu is empty

### ISSUE THREAD

**Issue by FieldofClay** [knrdl/hubleys-dashboard#51]
With the below configuration, Hubleys will not display a dashboard, when the user is not part of any of the groups that are defined within the menu.

```
  - title: Stuff
    allow: true
    menu:
      - title: Item1
        allow: [ group:users1 ]
      - title: Item2
        allow: [ group:users2 ]
      - title: Item3
        allow: [ group:users3 ]
```

If the user is not part of any of the above groups, I would expect Hubleys to not show the "Stuff" tile.

This can be worked around by explicitly defining each of the menu groups in the parent, however this requires updating the configuration in two spots when groups change.

```
  - title: Stuff
    allow: [ group:users1, group:users2, group:users3 ]
...
```

Logging output:
```
Listening on 0.0.0.0:3000
TypeError: Cannot read properties of undefined (reading 'some')
    at file:///app/server/chunks/_page.svelte-bdea7f04.js:422:407
    at Object.$$render (file:///app/server/chunks/index2-be719a76.js:111:18)
    at file:///app/server/chunks/_page.svelte-bdea7f04.js:570:48
    at each (file:///app/server/chunks/index2-be719a76.js:82:12)
    at file:///app/server/chunks/_page.svelte-bdea7f04.js:569:102
    at Object.$$render (file:///app/server/chunks/index2-be719a76.js:111:18)
    at Object.default (file:///app/server/index.js:89:97)
    at file:///app/server/chunks/_layout.svelte-62f868ba.js:4790:36
    at Object.$$render (file:///app/server/chunks/index2-be719a76.js:111:18)
    at file:///app/server/index.js:54:101
Server shutdown
```
